<?php

return [
    'styles' => [
        ['name' => 'Minimal Clean', 'slug' => 'minimal-clean', 'description' => 'Minimal putih bersih.', 'visual_mood' => 'clean', 'palette' => ['primary' => '#111827','secondary' => '#f8fafc','accent' => '#2563eb','text' => '#0f172a','background' => '#ffffff','surface' => '#f8fafc','muted' => 'rgba(15,23,42,0.64)'], 'font_preset' => 'Inter', 'radius' => '2xl', 'button_style' => 'rounded-lg', 'card_style' => 'clean-card', 'shadow_style' => 'soft', 'hero_style' => 'simple-convert', 'section_spacing' => 'balanced', 'background_pattern' => 'minimal-flat', 'badge_style' => 'clean-badge', 'image_treatment' => 'clean-frame'],
        ['name' => 'Clean Commerce', 'slug' => 'clean-commerce', 'description' => 'Netral sales-friendly.', 'visual_mood' => 'clean', 'palette' => ['primary' => '#0ea5e9','secondary' => '#e0f2fe','accent' => '#10b981','text' => '#f8fafc','background' => '#0f172a','surface' => '#1e293b','muted' => 'rgba(226,232,240,0.72)'], 'font_preset' => 'Plus Jakarta Sans', 'radius' => '2xl', 'button_style' => 'rounded-lg', 'card_style' => 'clean-card', 'shadow_style' => 'soft', 'hero_style' => 'simple-convert', 'section_spacing' => 'balanced', 'background_pattern' => 'soft-grid', 'badge_style' => 'clean-badge', 'image_treatment' => 'clean-frame'],
        ['name' => 'Soft White', 'slug' => 'soft-white', 'description' => 'Light lembut dengan banyak napas.', 'visual_mood' => 'minimal', 'palette' => ['primary' => '#6366f1','secondary' => '#eef2ff','accent' => '#a855f7','text' => '#1f2937','background' => '#fcfcfd','surface' => '#ffffff','muted' => 'rgba(31,41,55,0.62)'], 'font_preset' => 'Figtree', 'radius' => '3xl', 'button_style' => 'rounded-pill', 'card_style' => 'soft-panel', 'shadow_style' => 'soft', 'hero_style' => 'soft-showcase', 'section_spacing' => 'spacious', 'background_pattern' => 'soft-pattern', 'badge_style' => 'soft-pill', 'image_treatment' => 'soft-shadow'],
        ['name' => 'Neutral Workspace', 'slug' => 'neutral-workspace', 'description' => 'Workspace netral ala tool modern.', 'visual_mood' => 'minimal', 'palette' => ['primary' => '#334155','secondary' => '#f1f5f9','accent' => '#475569','text' => '#0f172a','background' => '#f8fafc','surface' => '#ffffff','muted' => 'rgba(15,23,42,0.58)'], 'font_preset' => 'Public Sans', 'radius' => 'xl', 'button_style' => 'rounded-lg', 'card_style' => 'workspace', 'shadow_style' => 'soft', 'hero_style' => 'simple-convert', 'section_spacing' => 'balanced', 'background_pattern' => 'minimal-flat', 'badge_style' => 'clean-badge', 'image_treatment' => 'flat'],
        ['name' => 'Notion Style', 'slug' => 'notion-style', 'description' => 'Rapi, ringan, utilitarian.', 'visual_mood' => 'minimal', 'palette' => ['primary' => '#111827','secondary' => '#f8fafc','accent' => '#6b7280','text' => '#111827','background' => '#ffffff','surface' => '#fafafa','muted' => 'rgba(17,24,39,0.60)'], 'font_preset' => 'DM Sans', 'radius' => 'xl', 'button_style' => 'rounded-lg', 'card_style' => 'notion', 'shadow_style' => 'none', 'hero_style' => 'simple-convert', 'section_spacing' => 'balanced', 'background_pattern' => 'minimal-flat', 'badge_style' => 'clean-badge', 'image_treatment' => 'flat'],

        ['name' => 'Mono Luxe', 'slug' => 'mono-luxe', 'description' => 'Editorial premium monokrom.', 'visual_mood' => 'premium', 'palette' => ['primary' => '#f8fafc','secondary' => '#e5e7eb','accent' => '#a1a1aa','text' => '#fafafa','background' => '#09090b','surface' => '#18181b','muted' => 'rgba(228,228,231,0.72)'], 'font_preset' => 'Playfair Display', 'radius' => 'xl', 'button_style' => 'luxury', 'card_style' => 'glass-dark', 'shadow_style' => 'deep', 'hero_style' => 'editorial', 'section_spacing' => 'luxury', 'background_pattern' => 'noise-texture', 'badge_style' => 'luxury-tag', 'image_treatment' => 'editorial-crop'],
        ['name' => 'Editorial Mode', 'slug' => 'editorial-mode', 'description' => 'Magazine style dengan serif kuat.', 'visual_mood' => 'premium', 'palette' => ['primary' => '#f5f5f4','secondary' => '#e7e5e4','accent' => '#c084fc','text' => '#fafaf9','background' => '#111827','surface' => '#1f2937','muted' => 'rgba(245,245,244,0.72)'], 'font_preset' => 'Cormorant Garamond', 'radius' => 'xl', 'button_style' => 'editorial', 'card_style' => 'editorial', 'shadow_style' => 'deep', 'hero_style' => 'editorial', 'section_spacing' => 'luxury', 'background_pattern' => 'noise-texture', 'badge_style' => 'editorial-chip', 'image_treatment' => 'editorial-crop'],
        ['name' => 'Royal Velvet', 'slug' => 'royal-velvet', 'description' => 'Rich premium high-ticket.', 'visual_mood' => 'premium', 'palette' => ['primary' => '#d4af37','secondary' => '#fef3c7','accent' => '#7c3aed','text' => '#faf5ff','background' => '#1e1b4b','surface' => '#312e81','muted' => 'rgba(233,213,255,0.72)'], 'font_preset' => 'Playfair Display', 'radius' => '2xl', 'button_style' => 'luxury', 'card_style' => 'luxury-card', 'shadow_style' => 'deep', 'hero_style' => 'prestige-estate', 'section_spacing' => 'luxury', 'background_pattern' => 'prestige-lines', 'badge_style' => 'royal-tag', 'image_treatment' => 'glossy'],
        ['name' => 'Black Gold Prestige', 'slug' => 'black-gold-prestige', 'description' => 'Black gold eksklusif.', 'visual_mood' => 'premium', 'palette' => ['primary' => '#eab308','secondary' => '#fde68a','accent' => '#f59e0b','text' => '#fefce8','background' => '#09090b','surface' => '#18181b','muted' => 'rgba(254,252,232,0.70)'], 'font_preset' => 'Bodoni Moda', 'radius' => 'xl', 'button_style' => 'luxury', 'card_style' => 'luxury-card', 'shadow_style' => 'deep', 'hero_style' => 'prestige-estate', 'section_spacing' => 'luxury', 'background_pattern' => 'prestige-lines', 'badge_style' => 'royal-tag', 'image_treatment' => 'glossy'],
        ['name' => 'Soft Luxury', 'slug' => 'soft-luxury', 'description' => 'Premium tapi tetap ringan.', 'visual_mood' => 'premium', 'palette' => ['primary' => '#d6bfa9','secondary' => '#f8f2ec','accent' => '#8b5e3c','text' => '#2f241f','background' => '#fffdfa','surface' => '#f8f2ec','muted' => 'rgba(47,36,31,0.62)'], 'font_preset' => 'Prata', 'radius' => '3xl', 'button_style' => 'luxury', 'card_style' => 'soft-panel', 'shadow_style' => 'soft', 'hero_style' => 'soft-showcase', 'section_spacing' => 'luxury', 'background_pattern' => 'soft-pattern', 'badge_style' => 'luxury-tag', 'image_treatment' => 'soft-shadow'],

        ['name' => 'Future Neon', 'slug' => 'future-neon', 'description' => 'Neon modern untuk digital launch.', 'visual_mood' => 'tech', 'palette' => ['primary' => '#16f2a5','secondary' => '#d1fae5','accent' => '#38bdf8','text' => '#ecfeff','background' => '#03111a','surface' => '#0c1a24','muted' => 'rgba(220,252,231,0.72)'], 'font_preset' => 'Space Grotesk', 'radius' => 'xl', 'button_style' => 'sharp', 'card_style' => 'neon-card', 'shadow_style' => 'neon', 'hero_style' => 'saas-split', 'section_spacing' => 'spacious', 'background_pattern' => 'grid-background', 'badge_style' => 'neon-chip', 'image_treatment' => 'glow'],
        ['name' => 'SaaS Split', 'slug' => 'saas-split', 'description' => 'Builder SaaS modern.', 'visual_mood' => 'tech', 'palette' => ['primary' => '#10b981','secondary' => '#d1fae5','accent' => '#38bdf8','text' => '#f0fdf4','background' => '#061018','surface' => '#0f172a','muted' => 'rgba(220,252,231,0.68)'], 'font_preset' => 'Plus Jakarta Sans', 'radius' => '2xl', 'button_style' => 'rounded-lg', 'card_style' => 'tech-card', 'shadow_style' => 'soft', 'hero_style' => 'saas-split', 'section_spacing' => 'balanced', 'background_pattern' => 'grid-background', 'badge_style' => 'clean-badge', 'image_treatment' => 'glow'],
        ['name' => 'Grid Glow', 'slug' => 'grid-glow', 'description' => 'Grid tech dengan glow kuat.', 'visual_mood' => 'tech', 'palette' => ['primary' => '#22d3ee','secondary' => '#cffafe','accent' => '#818cf8','text' => '#ecfeff','background' => '#0a0f1f','surface' => '#111827','muted' => 'rgba(207,250,254,0.72)'], 'font_preset' => 'Sora', 'radius' => 'xl', 'button_style' => 'sharp', 'card_style' => 'neon-card', 'shadow_style' => 'neon', 'hero_style' => 'saas-split', 'section_spacing' => 'balanced', 'background_pattern' => 'grid-background', 'badge_style' => 'neon-chip', 'image_treatment' => 'glow'],
        ['name' => 'Sharp Digital', 'slug' => 'sharp-digital', 'description' => 'Digital launch dengan sudut tegas.', 'visual_mood' => 'tech', 'palette' => ['primary' => '#06b6d4','secondary' => '#ecfeff','accent' => '#8b5cf6','text' => '#e0f2fe','background' => '#0f172a','surface' => '#111827','muted' => 'rgba(224,242,254,0.70)'], 'font_preset' => 'Outfit', 'radius' => 'lg', 'button_style' => 'sharp', 'card_style' => 'tech-card', 'shadow_style' => 'deep', 'hero_style' => 'saas-split', 'section_spacing' => 'balanced', 'background_pattern' => 'grid-background', 'badge_style' => 'sharp-tag', 'image_treatment' => 'glow'],
        ['name' => 'Crypto Surge', 'slug' => 'crypto-surge', 'description' => 'Crypto launch agresif.', 'visual_mood' => 'tech', 'palette' => ['primary' => '#22c55e','secondary' => '#dcfce7','accent' => '#14b8a6','text' => '#ecfdf5','background' => '#07120e','surface' => '#0f1f18','muted' => 'rgba(220,252,231,0.72)'], 'font_preset' => 'Space Grotesk', 'radius' => 'xl', 'button_style' => 'sharp', 'card_style' => 'neon-card', 'shadow_style' => 'neon', 'hero_style' => 'saas-split', 'section_spacing' => 'balanced', 'background_pattern' => 'grid-background', 'badge_style' => 'neon-chip', 'image_treatment' => 'glow'],
        ['name' => 'Indigo Launch', 'slug' => 'indigo-launch', 'description' => 'Indigo modern untuk launch.', 'visual_mood' => 'tech', 'palette' => ['primary' => '#818cf8','secondary' => '#e0e7ff','accent' => '#38bdf8','text' => '#eef2ff','background' => '#111827','surface' => '#1f2937','muted' => 'rgba(224,231,255,0.72)'], 'font_preset' => 'Manrope', 'radius' => '2xl', 'button_style' => 'rounded-lg', 'card_style' => 'glass-card', 'shadow_style' => 'soft', 'hero_style' => 'saas-split', 'section_spacing' => 'balanced', 'background_pattern' => 'grid-background', 'badge_style' => 'clean-badge', 'image_treatment' => 'glow'],
        ['name' => 'Glass Tech', 'slug' => 'glass-tech', 'description' => 'Glassmorphism tech look.', 'visual_mood' => 'tech', 'palette' => ['primary' => '#67e8f9','secondary' => '#ecfeff','accent' => '#c084fc','text' => '#f8fafc','background' => '#0f172a','surface' => '#1e293b','muted' => 'rgba(226,232,240,0.70)'], 'font_preset' => 'Urbanist', 'radius' => '3xl', 'button_style' => 'rounded-pill', 'card_style' => 'glass-card', 'shadow_style' => 'soft', 'hero_style' => 'saas-split', 'section_spacing' => 'spacious', 'background_pattern' => 'gradient', 'badge_style' => 'clean-badge', 'image_treatment' => 'glass'],
        ['name' => 'Cyber Mint', 'slug' => 'cyber-mint', 'description' => 'Mint cyber aesthetic.', 'visual_mood' => 'tech', 'palette' => ['primary' => '#34d399','secondary' => '#d1fae5','accent' => '#22d3ee','text' => '#ecfdf5','background' => '#03131a','surface' => '#0b1f25','muted' => 'rgba(209,250,229,0.72)'], 'font_preset' => 'Saira', 'radius' => 'xl', 'button_style' => 'sharp', 'card_style' => 'neon-card', 'shadow_style' => 'neon', 'hero_style' => 'saas-split', 'section_spacing' => 'balanced', 'background_pattern' => 'grid-background', 'badge_style' => 'neon-chip', 'image_treatment' => 'glow'],

        ['name' => 'Playful Pop', 'slug' => 'playful-pop', 'description' => 'Fun colorful aktif.', 'visual_mood' => 'fun', 'palette' => ['primary' => '#22c55e','secondary' => '#dcfce7','accent' => '#f472b6','text' => '#f8fafc','background' => '#111827','surface' => '#1f2937','muted' => 'rgba(220,252,231,0.72)'], 'font_preset' => 'Fredoka', 'radius' => '3xl', 'button_style' => 'rounded-pill', 'card_style' => 'play-card', 'shadow_style' => 'playful', 'hero_style' => 'promo-grid', 'section_spacing' => 'spacious', 'background_pattern' => 'gradient', 'badge_style' => 'play-chip', 'image_treatment' => 'soft-shadow'],
        ['name' => 'Candy Burst', 'slug' => 'candy-burst', 'description' => 'Vibrant candy look.', 'visual_mood' => 'fun', 'palette' => ['primary' => '#fb7185','secondary' => '#ffe4e6','accent' => '#60a5fa','text' => '#fff7ed','background' => '#3b0764','surface' => '#581c87','muted' => 'rgba(255,228,230,0.72)'], 'font_preset' => 'Baloo 2', 'radius' => '3xl', 'button_style' => 'rounded-pill', 'card_style' => 'play-card', 'shadow_style' => 'playful', 'hero_style' => 'promo-grid', 'section_spacing' => 'spacious', 'background_pattern' => 'gradient', 'badge_style' => 'play-chip', 'image_treatment' => 'soft-shadow'],
        ['name' => 'Joy Bloom', 'slug' => 'joy-bloom', 'description' => 'Ceriah, hangat, ringan.', 'visual_mood' => 'fun', 'palette' => ['primary' => '#f59e0b','secondary' => '#fef3c7','accent' => '#ec4899','text' => '#fff7ed','background' => '#3f1d0d','surface' => '#7c2d12','muted' => 'rgba(254,243,199,0.72)'], 'font_preset' => 'Nunito Sans', 'radius' => '3xl', 'button_style' => 'rounded-pill', 'card_style' => 'promo-card', 'shadow_style' => 'warm', 'hero_style' => 'promo-grid', 'section_spacing' => 'spacious', 'background_pattern' => 'gradient', 'badge_style' => 'promo-badge', 'image_treatment' => 'soft-shadow'],
        ['name' => 'Youth Vibe', 'slug' => 'youth-vibe', 'description' => 'Young and active.', 'visual_mood' => 'fun', 'palette' => ['primary' => '#a855f7','secondary' => '#f3e8ff','accent' => '#22c55e','text' => '#faf5ff','background' => '#1f2937','surface' => '#334155','muted' => 'rgba(243,232,255,0.72)'], 'font_preset' => 'Outfit', 'radius' => '2xl', 'button_style' => 'rounded-lg', 'card_style' => 'play-card', 'shadow_style' => 'soft', 'hero_style' => 'promo-grid', 'section_spacing' => 'balanced', 'background_pattern' => 'gradient', 'badge_style' => 'play-chip', 'image_treatment' => 'soft-shadow'],
        ['name' => 'Bright Motion', 'slug' => 'bright-motion', 'description' => 'High-energy promo look.', 'visual_mood' => 'fun', 'palette' => ['primary' => '#06b6d4','secondary' => '#cffafe','accent' => '#f59e0b','text' => '#ecfeff','background' => '#164e63','surface' => '#155e75','muted' => 'rgba(207,250,254,0.72)'], 'font_preset' => 'Archivo', 'radius' => '2xl', 'button_style' => 'sharp', 'card_style' => 'promo-card', 'shadow_style' => 'playful', 'hero_style' => 'promo-grid', 'section_spacing' => 'balanced', 'background_pattern' => 'gradient', 'badge_style' => 'promo-badge', 'image_treatment' => 'soft-shadow'],

        ['name' => 'Soft Bloom', 'slug' => 'soft-bloom', 'description' => 'Pastel soft feminine.', 'visual_mood' => 'beauty', 'palette' => ['primary' => '#f472b6','secondary' => '#fff1f5','accent' => '#c084fc','text' => '#4a2439','background' => '#fff8fb','surface' => '#fffdfd','muted' => 'rgba(74,36,57,0.68)'], 'font_preset' => 'Poppins', 'radius' => '3xl', 'button_style' => 'rounded-pill', 'card_style' => 'soft-panel', 'shadow_style' => 'soft', 'hero_style' => 'soft-showcase', 'section_spacing' => 'luxury', 'background_pattern' => 'soft-pattern', 'badge_style' => 'soft-pill', 'image_treatment' => 'soft-shadow'],
        ['name' => 'Rose Studio', 'slug' => 'rose-studio', 'description' => 'Rose beauty premium.', 'visual_mood' => 'beauty', 'palette' => ['primary' => '#fb7185','secondary' => '#fff1f2','accent' => '#fda4af','text' => '#4c0519','background' => '#fff8f8','surface' => '#fff1f2','muted' => 'rgba(76,5,25,0.60)'], 'font_preset' => 'DM Serif Display', 'radius' => '3xl', 'button_style' => 'rounded-pill', 'card_style' => 'soft-panel', 'shadow_style' => 'soft', 'hero_style' => 'soft-showcase', 'section_spacing' => 'luxury', 'background_pattern' => 'soft-pattern', 'badge_style' => 'soft-pill', 'image_treatment' => 'soft-shadow'],
        ['name' => 'Glow Skin', 'slug' => 'glow-skin', 'description' => 'Skincare look glowing.', 'visual_mood' => 'beauty', 'palette' => ['primary' => '#f59e0b','secondary' => '#fff7ed','accent' => '#f472b6','text' => '#7c2d12','background' => '#fffdf7','surface' => '#fff7ed','muted' => 'rgba(124,45,18,0.60)'], 'font_preset' => 'Poppins', 'radius' => '3xl', 'button_style' => 'rounded-pill', 'card_style' => 'soft-panel', 'shadow_style' => 'soft', 'hero_style' => 'soft-showcase', 'section_spacing' => 'luxury', 'background_pattern' => 'soft-pattern', 'badge_style' => 'soft-pill', 'image_treatment' => 'soft-shadow'],
        ['name' => 'Lavender Care', 'slug' => 'lavender-care', 'description' => 'Soft lavender care tone.', 'visual_mood' => 'beauty', 'palette' => ['primary' => '#a78bfa','secondary' => '#f5f3ff','accent' => '#f472b6','text' => '#312e81','background' => '#faf7ff','surface' => '#f5f3ff','muted' => 'rgba(49,46,129,0.60)'], 'font_preset' => 'Quicksand', 'radius' => '3xl', 'button_style' => 'rounded-pill', 'card_style' => 'soft-panel', 'shadow_style' => 'soft', 'hero_style' => 'soft-showcase', 'section_spacing' => 'luxury', 'background_pattern' => 'soft-pattern', 'badge_style' => 'soft-pill', 'image_treatment' => 'soft-shadow'],
        ['name' => 'Peach Soft', 'slug' => 'peach-soft', 'description' => 'Peach pastel calm.', 'visual_mood' => 'beauty', 'palette' => ['primary' => '#fb923c','secondary' => '#fff7ed','accent' => '#fdba74','text' => '#7c2d12','background' => '#fffaf5','surface' => '#fff7ed','muted' => 'rgba(124,45,18,0.60)'], 'font_preset' => 'Nunito Sans', 'radius' => '3xl', 'button_style' => 'rounded-pill', 'card_style' => 'soft-panel', 'shadow_style' => 'soft', 'hero_style' => 'soft-showcase', 'section_spacing' => 'luxury', 'background_pattern' => 'soft-pattern', 'badge_style' => 'soft-pill', 'image_treatment' => 'soft-shadow'],

        ['name' => 'Earth Craft', 'slug' => 'earth-craft', 'description' => 'Earthy natural.', 'visual_mood' => 'earthy', 'palette' => ['primary' => '#65a30d','secondary' => '#ecfccb','accent' => '#a16207','text' => '#fefce8','background' => '#1c1917','surface' => '#292524','muted' => 'rgba(236,252,203,0.72)'], 'font_preset' => 'Lora', 'radius' => '3xl', 'button_style' => 'rounded-lg', 'card_style' => 'organic-card', 'shadow_style' => 'warm', 'hero_style' => 'wellness-soft', 'section_spacing' => 'spacious', 'background_pattern' => 'soft-pattern', 'badge_style' => 'earth-badge', 'image_treatment' => 'natural'],
        ['name' => 'Nature Calm', 'slug' => 'nature-calm', 'description' => 'Fresh calm natural.', 'visual_mood' => 'earthy', 'palette' => ['primary' => '#22c55e','secondary' => '#dcfce7','accent' => '#0f766e','text' => '#14532d','background' => '#f7fff9','surface' => '#ecfdf5','muted' => 'rgba(20,83,45,0.62)'], 'font_preset' => 'Newsreader', 'radius' => '3xl', 'button_style' => 'rounded-pill', 'card_style' => 'organic-card', 'shadow_style' => 'soft', 'hero_style' => 'wellness-soft', 'section_spacing' => 'spacious', 'background_pattern' => 'soft-pattern', 'badge_style' => 'earth-badge', 'image_treatment' => 'natural'],
        ['name' => 'Herbal Warm', 'slug' => 'herbal-warm', 'description' => 'Herbal earthy warm.', 'visual_mood' => 'earthy', 'palette' => ['primary' => '#84cc16','secondary' => '#f7fee7','accent' => '#b45309','text' => '#365314','background' => '#fffdf7','surface' => '#fefce8','muted' => 'rgba(54,83,20,0.60)'], 'font_preset' => 'Merriweather', 'radius' => '2xl', 'button_style' => 'rounded-lg', 'card_style' => 'organic-card', 'shadow_style' => 'warm', 'hero_style' => 'wellness-soft', 'section_spacing' => 'spacious', 'background_pattern' => 'soft-pattern', 'badge_style' => 'earth-badge', 'image_treatment' => 'natural'],
        ['name' => 'Clay Mood', 'slug' => 'clay-mood', 'description' => 'Clay neutral natural.', 'visual_mood' => 'earthy', 'palette' => ['primary' => '#c2410c','secondary' => '#ffedd5','accent' => '#a16207','text' => '#431407','background' => '#fffaf5','surface' => '#ffedd5','muted' => 'rgba(67,20,7,0.62)'], 'font_preset' => 'Fraunces', 'radius' => '3xl', 'button_style' => 'rounded-lg', 'card_style' => 'organic-card', 'shadow_style' => 'warm', 'hero_style' => 'wellness-soft', 'section_spacing' => 'luxury', 'background_pattern' => 'soft-pattern', 'badge_style' => 'earth-badge', 'image_treatment' => 'natural'],

        ['name' => 'Bold Carbon', 'slug' => 'bold-carbon', 'description' => 'Dark masculine sharp.', 'visual_mood' => 'bold', 'palette' => ['primary' => '#f97316','secondary' => '#ffedd5','accent' => '#facc15','text' => '#fafaf9','background' => '#09090b','surface' => '#18181b','muted' => 'rgba(245,245,244,0.72)'], 'font_preset' => 'Rajdhani', 'radius' => 'xl', 'button_style' => 'sharp', 'card_style' => 'tech-card', 'shadow_style' => 'deep', 'hero_style' => 'bold-product', 'section_spacing' => 'balanced', 'background_pattern' => 'grid-background', 'badge_style' => 'sharp-tag', 'image_treatment' => 'high-contrast'],
        ['name' => 'Motor Force', 'slug' => 'motor-force', 'description' => 'Automotive bold sales.', 'visual_mood' => 'bold', 'palette' => ['primary' => '#ef4444','secondary' => '#fee2e2','accent' => '#f97316','text' => '#fff7ed','background' => '#111827','surface' => '#1f2937','muted' => 'rgba(254,226,226,0.68)'], 'font_preset' => 'Barlow Condensed', 'radius' => 'xl', 'button_style' => 'sharp', 'card_style' => 'tech-card', 'shadow_style' => 'deep', 'hero_style' => 'stock-banner', 'section_spacing' => 'balanced', 'background_pattern' => 'grid-background', 'badge_style' => 'sharp-tag', 'image_treatment' => 'high-contrast'],
        ['name' => 'Iron Grid', 'slug' => 'iron-grid', 'description' => 'Industrial masculine.', 'visual_mood' => 'bold', 'palette' => ['primary' => '#94a3b8','secondary' => '#e2e8f0','accent' => '#f59e0b','text' => '#f8fafc','background' => '#0f172a','surface' => '#1e293b','muted' => 'rgba(226,232,240,0.72)'], 'font_preset' => 'Oswald', 'radius' => 'lg', 'button_style' => 'sharp', 'card_style' => 'tech-card', 'shadow_style' => 'deep', 'hero_style' => 'bold-product', 'section_spacing' => 'balanced', 'background_pattern' => 'grid-background', 'badge_style' => 'sharp-tag', 'image_treatment' => 'high-contrast'],
        ['name' => 'Urban Bold', 'slug' => 'urban-bold', 'description' => 'Street bold visual.', 'visual_mood' => 'bold', 'palette' => ['primary' => '#22c55e','secondary' => '#dcfce7','accent' => '#f97316','text' => '#f8fafc','background' => '#111827','surface' => '#1f2937','muted' => 'rgba(220,252,231,0.68)'], 'font_preset' => 'Bebas Neue', 'radius' => 'xl', 'button_style' => 'sharp', 'card_style' => 'tech-card', 'shadow_style' => 'deep', 'hero_style' => 'editorial', 'section_spacing' => 'balanced', 'background_pattern' => 'grid-background', 'badge_style' => 'sharp-tag', 'image_treatment' => 'high-contrast'],
        ['name' => 'Dark Impact', 'slug' => 'dark-impact', 'description' => 'Dark direct conversion.', 'visual_mood' => 'bold', 'palette' => ['primary' => '#f43f5e','secondary' => '#ffe4e6','accent' => '#fb7185','text' => '#fff1f2','background' => '#18181b','surface' => '#27272a','muted' => 'rgba(255,228,230,0.70)'], 'font_preset' => 'Anton', 'radius' => 'lg', 'button_style' => 'sharp', 'card_style' => 'tech-card', 'shadow_style' => 'deep', 'hero_style' => 'bold-product', 'section_spacing' => 'balanced', 'background_pattern' => 'grid-background', 'badge_style' => 'sharp-tag', 'image_treatment' => 'high-contrast'],

        ['name' => 'Sunset Punch', 'slug' => 'sunset-punch', 'description' => 'Warm energetic promo.', 'visual_mood' => 'promo', 'palette' => ['primary' => '#fb923c','secondary' => '#ffedd5','accent' => '#ef4444','text' => '#fff7ed','background' => '#2a1207','surface' => '#3c1b0d','muted' => 'rgba(255,237,213,0.72)'], 'font_preset' => 'Poppins', 'radius' => '2xl', 'button_style' => 'rounded-pill', 'card_style' => 'promo-card', 'shadow_style' => 'warm', 'hero_style' => 'promo-grid', 'section_spacing' => 'spacious', 'background_pattern' => 'gradient', 'badge_style' => 'promo-badge', 'image_treatment' => 'warm-glow'],
        ['name' => 'Flash Sale Heat', 'slug' => 'flash-sale-heat', 'description' => 'Urgent flash sale look.', 'visual_mood' => 'promo', 'palette' => ['primary' => '#ef4444','secondary' => '#fee2e2','accent' => '#f59e0b','text' => '#fff7ed','background' => '#450a0a','surface' => '#7f1d1d','muted' => 'rgba(254,226,226,0.72)'], 'font_preset' => 'Archivo', 'radius' => 'xl', 'button_style' => 'sharp', 'card_style' => 'promo-card', 'shadow_style' => 'warm', 'hero_style' => 'promo-grid', 'section_spacing' => 'balanced', 'background_pattern' => 'gradient', 'badge_style' => 'promo-badge', 'image_treatment' => 'warm-glow'],
        ['name' => 'Warm Commerce', 'slug' => 'warm-commerce', 'description' => 'Sales page warm.', 'visual_mood' => 'promo', 'palette' => ['primary' => '#f59e0b','secondary' => '#fef3c7','accent' => '#16a34a','text' => '#78350f','background' => '#fffaf0','surface' => '#fffbeb','muted' => 'rgba(120,53,15,0.64)'], 'font_preset' => 'Cabin', 'radius' => '2xl', 'button_style' => 'rounded-lg', 'card_style' => 'promo-card', 'shadow_style' => 'soft', 'hero_style' => 'simple-convert', 'section_spacing' => 'balanced', 'background_pattern' => 'soft-pattern', 'badge_style' => 'promo-badge', 'image_treatment' => 'warm-glow'],
        ['name' => 'Orange Promo', 'slug' => 'orange-promo', 'description' => 'Orange conversion mode.', 'visual_mood' => 'promo', 'palette' => ['primary' => '#f97316','secondary' => '#ffedd5','accent' => '#ea580c','text' => '#fff7ed','background' => '#431407','surface' => '#7c2d12','muted' => 'rgba(255,237,213,0.72)'], 'font_preset' => 'Montserrat', 'radius' => 'xl', 'button_style' => 'rounded-pill', 'card_style' => 'promo-card', 'shadow_style' => 'warm', 'hero_style' => 'promo-grid', 'section_spacing' => 'balanced', 'background_pattern' => 'gradient', 'badge_style' => 'promo-badge', 'image_treatment' => 'warm-glow'],

        ['name' => 'Ocean Glass', 'slug' => 'ocean-glass', 'description' => 'Fresh airy clean modern.', 'visual_mood' => 'fresh', 'palette' => ['primary' => '#06b6d4','secondary' => '#cffafe','accent' => '#60a5fa','text' => '#ecfeff','background' => '#082f49','surface' => '#0c4a6e','muted' => 'rgba(207,250,254,0.72)'], 'font_preset' => 'Plus Jakarta Sans', 'radius' => '2xl', 'button_style' => 'rounded-pill', 'card_style' => 'glass-card', 'shadow_style' => 'soft', 'hero_style' => 'destination-banner', 'section_spacing' => 'spacious', 'background_pattern' => 'gradient', 'badge_style' => 'clean-tag', 'image_treatment' => 'glass'],
        ['name' => 'Sky Fresh', 'slug' => 'sky-fresh', 'description' => 'Fresh light health look.', 'visual_mood' => 'fresh', 'palette' => ['primary' => '#38bdf8','secondary' => '#e0f2fe','accent' => '#22c55e','text' => '#0c4a6e','background' => '#f8fdff','surface' => '#f0f9ff','muted' => 'rgba(12,74,110,0.62)'], 'font_preset' => 'Onest', 'radius' => '3xl', 'button_style' => 'rounded-pill', 'card_style' => 'glass-card', 'shadow_style' => 'soft', 'hero_style' => 'clinic-trust', 'section_spacing' => 'spacious', 'background_pattern' => 'light-clean', 'badge_style' => 'clean-badge', 'image_treatment' => 'glass'],
        ['name' => 'Aqua Clinic', 'slug' => 'aqua-clinic', 'description' => 'Clinic and trust oriented.', 'visual_mood' => 'fresh', 'palette' => ['primary' => '#14b8a6','secondary' => '#ccfbf1','accent' => '#60a5fa','text' => '#134e4a','background' => '#f7fffd','surface' => '#f0fdfa','muted' => 'rgba(19,78,74,0.62)'], 'font_preset' => 'Work Sans', 'radius' => '2xl', 'button_style' => 'rounded-lg', 'card_style' => 'glass-card', 'shadow_style' => 'soft', 'hero_style' => 'clinic-trust', 'section_spacing' => 'spacious', 'background_pattern' => 'light-clean', 'badge_style' => 'clean-badge', 'image_treatment' => 'glass'],
    ],
];
