<?php

return [
    'default' => [
        'label' => 'UMKM Umum',
        'visual_mood' => 'clean-conversion',
        'palette' => [
            'primary' => '#10b981',
            'secondary' => '#d1fae5',
            'accent' => '#34d399',
            'text' => '#ecfdf5',
            'background' => '#07110f',
            'surface' => '#0c1714',
            'muted' => 'rgba(209, 250, 229, 0.72)',
        ],
        'font' => 'Plus Jakarta Sans',
        'button_style' => 'rounded-pill',
        'hero_style' => 'simple-convert',
        'heading_scale' => 'lg',
        'section_order' => ['comparison', 'benefits', 'features', 'testimonials', 'pricing', 'faq', 'cta'],
        'recommended_sections' => ['hero', 'comparison', 'benefits', 'features', 'testimonials', 'pricing', 'faq', 'cta'],
        'copy_tone' => 'jelas, to the point, conversion-focused',
        'cta_style' => 'solid-bright',
        'trust_elements' => ['Siap pakai', 'Mudah diedit', 'CTA langsung aktif'],
        'card_radius' => '2xl',
        'spacing_density' => 'normal',
        'background_pattern' => 'grid-glow',
        'layout_style' => 'balanced',
        'icon_style' => 'soft-glow',
    ],
    'visual_presets' => [
        'crypto-surge' => [
            'label' => 'Crypto Surge',
            'description' => 'Neon dark, tech-heavy, agresif, cocok untuk crypto class dan digital launch.',
            'theme' => [
                'palette' => ['primary' => '#16f2a5', 'secondary' => '#c9ffe6', 'accent' => '#3b82f6', 'text' => '#effff8', 'background' => '#07110f', 'surface' => '#0c1714', 'muted' => 'rgba(201, 255, 230, 0.72)'],
                'font' => 'Space Grotesk',
                'button_style' => 'sharp',
                'hero_style' => 'saas-split',
                'heading_scale' => 'xxl',
                'spacing_density' => 'comfortable',
                'background_pattern' => 'grid-glow',
                'layout_style' => 'product-led',
                'icon_style' => 'gradient-chip',
            ],
        ],
        'luxury-property' => [
            'label' => 'Luxury Property',
            'description' => 'Prestige, dark navy, gold accent, high-ticket dan eksklusif.',
            'theme' => [
                'palette' => ['primary' => '#d4af37', 'secondary' => '#fef3c7', 'accent' => '#60a5fa', 'text' => '#f8fafc', 'background' => '#081120', 'surface' => '#111c31', 'muted' => 'rgba(226, 232, 240, 0.72)'],
                'font' => 'Playfair Display',
                'button_style' => 'luxury',
                'hero_style' => 'prestige-estate',
                'heading_scale' => 'xxl',
                'spacing_density' => 'airy',
                'background_pattern' => 'prestige-lines',
                'layout_style' => 'high-ticket',
                'icon_style' => 'gold-frame',
            ],
        ],
        'beauty-soft' => [
            'label' => 'Beauty Soft',
            'description' => 'Pastel premium, lembut, glowing, cocok untuk skincare dan beauty service.',
            'theme' => [
                'palette' => ['primary' => '#f472b6', 'secondary' => '#fff1f5', 'accent' => '#d8b4fe', 'text' => '#512b42', 'background' => '#fff8fb', 'surface' => '#fffdfd', 'muted' => 'rgba(81, 43, 66, 0.68)'],
                'font' => 'Poppins',
                'button_style' => 'rounded-pill',
                'hero_style' => 'soft-showcase',
                'heading_scale' => 'xl',
                'spacing_density' => 'airy',
                'background_pattern' => 'soft-blur',
                'layout_style' => 'visual-heavy',
                'icon_style' => 'rounded-soft',
            ],
        ],
        'automotive-bold' => [
            'label' => 'Automotive Bold',
            'description' => 'Kontras kuat, maskulin, tajam, cocok untuk otomotif, helm, dan motor.',
            'theme' => [
                'palette' => ['primary' => '#ff5b1f', 'secondary' => '#ffe1d4', 'accent' => '#ef4444', 'text' => '#fff7ed', 'background' => '#090909', 'surface' => '#141414', 'muted' => 'rgba(255, 225, 212, 0.7)'],
                'font' => 'Rajdhani',
                'button_style' => 'sharp',
                'hero_style' => 'bold-product',
                'heading_scale' => 'xxl',
                'spacing_density' => 'compact',
                'background_pattern' => 'grid-industrial',
                'layout_style' => 'feature-driven',
                'icon_style' => 'tech-frame',
            ],
        ],
    ],
    'preset_map' => [
        'digital-product' => ['crypto-surge'],
        'edukasi-course' => ['crypto-surge'],
        'agency-studio-design' => ['crypto-surge'],
        'properti' => ['luxury-property'],
        'skincare' => ['beauty-soft'],
        'salon-beauty-service' => ['beauty-soft'],
        'helm' => ['automotive-bold'],
        'motor-jual-beli' => ['automotive-bold'],
        'otomotif-bengkel' => ['automotive-bold'],
        'gadget-elektronik' => ['automotive-bold'],
    ],
    'niches' => [
        'digital-product' => [
            'label' => 'Digital Product',
            'visual_mood' => 'modern-saas',
            'palette' => ['primary' => '#7c3aed', 'secondary' => '#ede9fe', 'accent' => '#38bdf8', 'text' => '#eef2ff', 'background' => '#0b1020', 'surface' => '#121934', 'muted' => 'rgba(224, 231, 255, 0.72)'],
            'font' => 'Plus Jakarta Sans',
            'button_style' => 'rounded-pill',
            'hero_style' => 'saas-split',
            'heading_scale' => 'xl',
            'section_order' => ['stats', 'benefits', 'features', 'package', 'testimonials', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'stats', 'benefits', 'features', 'package', 'testimonials', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'tegas, modern, simpel',
            'cta_style' => 'glow-solid',
            'trust_elements' => ['Instant access', 'Akses lifetime', 'Template siap pakai'],
            'card_radius' => '3xl',
            'spacing_density' => 'comfortable',
            'background_pattern' => 'grid-glow',
            'layout_style' => 'product-led',
            'icon_style' => 'gradient-chip',
        ],
        'skincare' => [
            'label' => 'Skincare',
            'visual_mood' => 'soft-premium',
            'palette' => ['primary' => '#f472b6', 'secondary' => '#fdf2f8', 'accent' => '#c084fc', 'text' => '#4a2439', 'background' => '#fff7fb', 'surface' => '#fffafc', 'muted' => 'rgba(74, 36, 57, 0.68)'],
            'font' => 'Poppins',
            'button_style' => 'rounded-pill',
            'hero_style' => 'soft-showcase',
            'heading_scale' => 'lg',
            'section_order' => ['before_after', 'benefits', 'features', 'testimonials', 'gallery', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'before_after', 'benefits', 'features', 'testimonials', 'gallery', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'soft persuasive, aspiratif, beauty-oriented',
            'cta_style' => 'soft-solid',
            'trust_elements' => ['Best seller', 'Aman dipakai harian', 'Glow look'],
            'card_radius' => '3xl',
            'spacing_density' => 'airy',
            'background_pattern' => 'soft-blur',
            'layout_style' => 'visual-heavy',
            'icon_style' => 'rounded-soft',
        ],
        'jasa' => [
            'label' => 'Jasa',
            'visual_mood' => 'professional-trust',
            'palette' => ['primary' => '#0f766e', 'secondary' => '#ccfbf1', 'accent' => '#22c55e', 'text' => '#ecfeff', 'background' => '#071313', 'surface' => '#0e1c1d', 'muted' => 'rgba(204, 251, 241, 0.7)'],
            'font' => 'Plus Jakarta Sans',
            'button_style' => 'rounded-lg',
            'hero_style' => 'trust-stack',
            'heading_scale' => 'lg',
            'section_order' => ['trust_badges', 'comparison', 'benefits', 'process', 'gallery', 'testimonials', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'trust_badges', 'comparison', 'benefits', 'process', 'gallery', 'testimonials', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'profesional, meyakinkan, jelas',
            'cta_style' => 'consultation',
            'trust_elements' => ['Konsultasi cepat', 'Trusted service', 'Result-oriented'],
            'card_radius' => '2xl',
            'spacing_density' => 'structured',
            'background_pattern' => 'grid-subtle',
            'layout_style' => 'text-first',
            'icon_style' => 'badge-clean',
        ],
        'travel' => [
            'label' => 'Travel',
            'visual_mood' => 'aspirational-exciting',
            'palette' => ['primary' => '#0ea5e9', 'secondary' => '#e0f2fe', 'accent' => '#fb923c', 'text' => '#f8fafc', 'background' => '#082032', 'surface' => '#11324a', 'muted' => 'rgba(226, 232, 240, 0.76)'],
            'font' => 'Poppins',
            'button_style' => 'rounded-pill',
            'hero_style' => 'destination-banner',
            'heading_scale' => 'xl',
            'section_order' => ['gallery', 'itinerary', 'package', 'benefits', 'testimonials', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'gallery', 'itinerary', 'package', 'benefits', 'testimonials', 'faq', 'cta'],
            'copy_tone' => 'exciting, inspiratif, ringan',
            'cta_style' => 'booking-strong',
            'trust_elements' => ['Open trip siap berangkat', 'Itinerary jelas', 'Booking mudah'],
            'card_radius' => '3xl',
            'spacing_density' => 'airy',
            'background_pattern' => 'sunset-fade',
            'layout_style' => 'immersive',
            'icon_style' => 'travel-chip',
        ],
        'helm' => [
            'label' => 'Helm',
            'visual_mood' => 'bold-safety',
            'palette' => ['primary' => '#f97316', 'secondary' => '#ffedd5', 'accent' => '#ef4444', 'text' => '#fff7ed', 'background' => '#0c0a09', 'surface' => '#171210', 'muted' => 'rgba(255, 237, 213, 0.7)'],
            'font' => 'Rajdhani',
            'button_style' => 'sharp',
            'hero_style' => 'bold-product',
            'heading_scale' => 'xxl',
            'section_order' => ['stats', 'features', 'comparison', 'gallery', 'testimonials', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'stats', 'features', 'comparison', 'gallery', 'testimonials', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'maskulin, yakin, langsung',
            'cta_style' => 'high-contrast',
            'trust_elements' => ['Safety first', 'Best seller', 'Siap kirim cepat'],
            'card_radius' => 'xl',
            'spacing_density' => 'compact',
            'background_pattern' => 'grid-industrial',
            'layout_style' => 'feature-driven',
            'icon_style' => 'tech-frame',
        ],
        'motor-jual-beli' => [
            'label' => 'Motor Jual Beli',
            'visual_mood' => 'trust-transactional',
            'palette' => ['primary' => '#ef4444', 'secondary' => '#fee2e2', 'accent' => '#f59e0b', 'text' => '#f9fafb', 'background' => '#0b0b0d', 'surface' => '#15161a', 'muted' => 'rgba(229, 231, 235, 0.72)'],
            'font' => 'Rajdhani',
            'button_style' => 'sharp',
            'hero_style' => 'stock-banner',
            'heading_scale' => 'xl',
            'section_order' => ['stats', 'trust_badges', 'gallery', 'comparison', 'process', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'stats', 'trust_badges', 'gallery', 'comparison', 'process', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'praktis, lugas, meyakinkan',
            'cta_style' => 'chat-fast',
            'trust_elements' => ['Stok jelas', 'Simulasi ringan', 'Chat cepat'],
            'card_radius' => 'xl',
            'spacing_density' => 'compact',
            'background_pattern' => 'grid-industrial',
            'layout_style' => 'transaksional',
            'icon_style' => 'badge-strong',
        ],
        'fashion' => [
            'label' => 'Fashion',
            'visual_mood' => 'editorial-stylish',
            'palette' => ['primary' => '#eab308', 'secondary' => '#fef9c3', 'accent' => '#84cc16', 'text' => '#fafaf9', 'background' => '#111111', 'surface' => '#1c1c1c', 'muted' => 'rgba(231, 229, 228, 0.7)'],
            'font' => 'Cormorant Garamond',
            'button_style' => 'editorial',
            'hero_style' => 'editorial',
            'heading_scale' => 'xxl',
            'section_order' => ['gallery', 'benefits', 'features', 'testimonials', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'gallery', 'benefits', 'features', 'testimonials', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'confident, stylish, brand-first',
            'cta_style' => 'shop-now',
            'trust_elements' => ['New drop', 'Limited release', 'Lookbook ready'],
            'card_radius' => 'xl',
            'spacing_density' => 'airy',
            'background_pattern' => 'editorial-noise',
            'layout_style' => 'image-led',
            'icon_style' => 'minimal-line',
        ],
        'makanan-minuman' => [
            'label' => 'Makanan / Minuman',
            'visual_mood' => 'promo-appetizing',
            'palette' => ['primary' => '#f97316', 'secondary' => '#ffedd5', 'accent' => '#facc15', 'text' => '#fff7ed', 'background' => '#2a1308', 'surface' => '#3a1b0d', 'muted' => 'rgba(254, 215, 170, 0.78)'],
            'font' => 'Poppins',
            'button_style' => 'rounded-pill',
            'hero_style' => 'promo-grid',
            'heading_scale' => 'xl',
            'section_order' => ['gallery', 'package', 'benefits', 'testimonials', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'gallery', 'package', 'benefits', 'testimonials', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'menggoda, cepat, ringan',
            'cta_style' => 'order-fast',
            'trust_elements' => ['Best seller', 'Siap antar', 'Promo hari ini'],
            'card_radius' => '2xl',
            'spacing_density' => 'comfortable',
            'background_pattern' => 'warm-fade',
            'layout_style' => 'promo-led',
            'icon_style' => 'chip-bright',
        ],
        'furniture' => [
            'label' => 'Furniture',
            'visual_mood' => 'warm-premium',
            'palette' => ['primary' => '#a16207', 'secondary' => '#fef3c7', 'accent' => '#d97706', 'text' => '#fefce8', 'background' => '#1f1712', 'surface' => '#2d2119', 'muted' => 'rgba(253, 230, 138, 0.68)'],
            'font' => 'Lora',
            'button_style' => 'rounded-lg',
            'hero_style' => 'warm-room',
            'heading_scale' => 'lg',
            'section_order' => ['gallery', 'features', 'benefits', 'testimonials', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'gallery', 'features', 'benefits', 'testimonials', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'hangat, premium, berkelas',
            'cta_style' => 'consult-soft',
            'trust_elements' => ['Material pilihan', 'Finishing rapi', 'Konsultasi custom'],
            'card_radius' => '3xl',
            'spacing_density' => 'airy',
            'background_pattern' => 'linen',
            'layout_style' => 'spacious',
            'icon_style' => 'wood-badge',
        ],
        'properti' => [
            'label' => 'Properti',
            'visual_mood' => 'prestige-luxury',
            'palette' => ['primary' => '#d4af37', 'secondary' => '#fef3c7', 'accent' => '#60a5fa', 'text' => '#f8fafc', 'background' => '#0f172a', 'surface' => '#1e293b', 'muted' => 'rgba(226, 232, 240, 0.72)'],
            'font' => 'Playfair Display',
            'button_style' => 'luxury',
            'hero_style' => 'prestige-estate',
            'heading_scale' => 'xl',
            'section_order' => ['stats', 'gallery', 'features', 'comparison', 'package', 'testimonials', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'stats', 'gallery', 'features', 'comparison', 'package', 'testimonials', 'faq', 'cta'],
            'copy_tone' => 'eksklusif, meyakinkan, elegan',
            'cta_style' => 'survey-cta',
            'trust_elements' => ['Lokasi strategis', 'Nilai investasi', 'Survey mudah'],
            'card_radius' => '2xl',
            'spacing_density' => 'airy',
            'background_pattern' => 'prestige-lines',
            'layout_style' => 'high-ticket',
            'icon_style' => 'gold-frame',
        ],
        'event-wedding' => [
            'label' => 'Event / Wedding',
            'visual_mood' => 'romantic-elegant',
            'palette' => ['primary' => '#f9a8d4', 'secondary' => '#fdf2f8', 'accent' => '#a3b18a', 'text' => '#4a2f3f', 'background' => '#fffaf5', 'surface' => '#fffdfb', 'muted' => 'rgba(74, 47, 63, 0.68)'],
            'font' => 'Cormorant Garamond',
            'button_style' => 'rounded-pill',
            'hero_style' => 'story-gallery',
            'heading_scale' => 'lg',
            'section_order' => ['gallery', 'package', 'process', 'testimonials', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'gallery', 'package', 'process', 'testimonials', 'faq', 'cta'],
            'copy_tone' => 'emosional, manis, meyakinkan',
            'cta_style' => 'consultation-soft',
            'trust_elements' => ['Tanggal fleksibel', 'Konsep personal', 'Tim berpengalaman'],
            'card_radius' => '3xl',
            'spacing_density' => 'airy',
            'background_pattern' => 'soft-blur',
            'layout_style' => 'storytelling',
            'icon_style' => 'romance-chip',
        ],
        'edukasi-course' => [
            'label' => 'Edukasi / Course',
            'visual_mood' => 'transformational-clear',
            'palette' => ['primary' => '#22c55e', 'secondary' => '#dcfce7', 'accent' => '#3b82f6', 'text' => '#ecfdf5', 'background' => '#07130b', 'surface' => '#0f1e14', 'muted' => 'rgba(220, 252, 231, 0.72)'],
            'font' => 'Plus Jakarta Sans',
            'button_style' => 'rounded-pill',
            'hero_style' => 'mentor-led',
            'heading_scale' => 'xl',
            'section_order' => ['stats', 'comparison', 'benefits', 'features', 'process', 'testimonials', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'stats', 'comparison', 'benefits', 'features', 'process', 'testimonials', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'edukatif, memotivasi, tegas',
            'cta_style' => 'enroll',
            'trust_elements' => ['Belajar terstruktur', 'Cocok pemula', 'Progress jelas'],
            'card_radius' => '2xl',
            'spacing_density' => 'comfortable',
            'background_pattern' => 'grid-glow',
            'layout_style' => 'curriculum-first',
            'icon_style' => 'learning-badge',
        ],
        'gadget-elektronik' => [
            'label' => 'Gadget / Elektronik',
            'visual_mood' => 'tech-sleek',
            'palette' => ['primary' => '#38bdf8', 'secondary' => '#e0f2fe', 'accent' => '#94a3b8', 'text' => '#f8fafc', 'background' => '#020617', 'surface' => '#0f172a', 'muted' => 'rgba(226, 232, 240, 0.7)'],
            'font' => 'Rajdhani',
            'button_style' => 'sharp',
            'hero_style' => 'tech-spec',
            'heading_scale' => 'xxl',
            'section_order' => ['stats', 'features', 'comparison', 'gallery', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'stats', 'features', 'comparison', 'gallery', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'tech-savvy, clear, modern',
            'cta_style' => 'buy-now',
            'trust_elements' => ['Garansi resmi', 'Spesifikasi jelas', 'Stok update'],
            'card_radius' => 'xl',
            'spacing_density' => 'compact',
            'background_pattern' => 'grid-industrial',
            'layout_style' => 'spec-driven',
            'icon_style' => 'tech-frame',
        ],
        'kesehatan-klinik' => [
            'label' => 'Kesehatan / Klinik',
            'visual_mood' => 'calm-clean',
            'palette' => ['primary' => '#14b8a6', 'secondary' => '#ccfbf1', 'accent' => '#60a5fa', 'text' => '#ecfeff', 'background' => '#071417', 'surface' => '#0d1f24', 'muted' => 'rgba(207, 250, 254, 0.72)'],
            'font' => 'Plus Jakarta Sans',
            'button_style' => 'rounded-lg',
            'hero_style' => 'clinic-trust',
            'heading_scale' => 'lg',
            'section_order' => ['trust_badges', 'benefits', 'process', 'testimonials', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'trust_badges', 'benefits', 'process', 'testimonials', 'faq', 'cta'],
            'copy_tone' => 'tenang, profesional, reassuring',
            'cta_style' => 'consultation',
            'trust_elements' => ['Tenaga ahli', 'Pelayanan aman', 'Konsultasi mudah'],
            'card_radius' => '2xl',
            'spacing_density' => 'comfortable',
            'background_pattern' => 'soft-grid',
            'layout_style' => 'trust-first',
            'icon_style' => 'clinic-badge',
        ],
        'salon-beauty-service' => [
            'label' => 'Salon / Beauty Service',
            'visual_mood' => 'fresh-premium',
            'palette' => ['primary' => '#fb7185', 'secondary' => '#ffe4e6', 'accent' => '#f9a8d4', 'text' => '#fff1f2', 'background' => '#23131a', 'surface' => '#331824', 'muted' => 'rgba(255, 228, 230, 0.72)'],
            'font' => 'Poppins',
            'button_style' => 'rounded-pill',
            'hero_style' => 'beauty-showcase',
            'heading_scale' => 'lg',
            'section_order' => ['before_after', 'gallery', 'benefits', 'package', 'testimonials', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'before_after', 'gallery', 'benefits', 'package', 'testimonials', 'faq', 'cta'],
            'copy_tone' => 'lembut, cantik, persuasif',
            'cta_style' => 'booking-soft',
            'trust_elements' => ['Slot terbatas', 'Treatment premium', 'Booking cepat'],
            'card_radius' => '3xl',
            'spacing_density' => 'airy',
            'background_pattern' => 'soft-blur',
            'layout_style' => 'visual-heavy',
            'icon_style' => 'rounded-soft',
        ],
        'otomotif-bengkel' => [
            'label' => 'Otomotif Bengkel',
            'visual_mood' => 'functional-strong',
            'palette' => ['primary' => '#facc15', 'secondary' => '#fef9c3', 'accent' => '#ef4444', 'text' => '#fefce8', 'background' => '#111111', 'surface' => '#1d1d1d', 'muted' => 'rgba(254, 249, 195, 0.68)'],
            'font' => 'Rajdhani',
            'button_style' => 'sharp',
            'hero_style' => 'workshop-bold',
            'heading_scale' => 'xl',
            'section_order' => ['trust_badges', 'features', 'process', 'testimonials', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'trust_badges', 'features', 'process', 'testimonials', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'lugas, cepat, terpercaya',
            'cta_style' => 'booking-fast',
            'trust_elements' => ['Servis cepat', 'Teknisi berpengalaman', 'Booking WhatsApp'],
            'card_radius' => 'xl',
            'spacing_density' => 'compact',
            'background_pattern' => 'grid-industrial',
            'layout_style' => 'service-action',
            'icon_style' => 'badge-strong',
        ],
        'herbal-wellness' => [
            'label' => 'Herbal / Wellness',
            'visual_mood' => 'natural-calm',
            'palette' => ['primary' => '#65a30d', 'secondary' => '#ecfccb', 'accent' => '#a16207', 'text' => '#f7fee7', 'background' => '#111913', 'surface' => '#1a261d', 'muted' => 'rgba(236, 252, 203, 0.72)'],
            'font' => 'Lora',
            'button_style' => 'rounded-pill',
            'hero_style' => 'wellness-soft',
            'heading_scale' => 'lg',
            'section_order' => ['benefits', 'features', 'testimonials', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'benefits', 'features', 'testimonials', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'natural, menenangkan, edukatif ringan',
            'cta_style' => 'order-soft',
            'trust_elements' => ['Bahan alami', 'Rasa nyaman', 'Cocok konsumsi rutin'],
            'card_radius' => '3xl',
            'spacing_density' => 'airy',
            'background_pattern' => 'organic-wash',
            'layout_style' => 'natural-flow',
            'icon_style' => 'leaf-badge',
        ],
        'umkm-umum' => [
            'label' => 'UMKM Umum',
            'visual_mood' => 'clean-conversion',
            'palette' => ['primary' => '#0ea5e9', 'secondary' => '#e0f2fe', 'accent' => '#10b981', 'text' => '#ecfeff', 'background' => '#08131c', 'surface' => '#10202b', 'muted' => 'rgba(224, 242, 254, 0.72)'],
            'font' => 'Plus Jakarta Sans',
            'button_style' => 'rounded-lg',
            'hero_style' => 'simple-convert',
            'heading_scale' => 'lg',
            'section_order' => ['comparison', 'benefits', 'features', 'testimonials', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'comparison', 'benefits', 'features', 'testimonials', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'umum, jelas, to the point',
            'cta_style' => 'solid-bright',
            'trust_elements' => ['Siap promosi', 'Lebih profesional', 'Mudah dipahami'],
            'card_radius' => '2xl',
            'spacing_density' => 'normal',
            'background_pattern' => 'soft-grid',
            'layout_style' => 'balanced',
            'icon_style' => 'soft-glow',
        ],
        'personal-branding' => [
            'label' => 'Personal Branding',
            'visual_mood' => 'authority-human',
            'palette' => ['primary' => '#eab308', 'secondary' => '#fefce8', 'accent' => '#f97316', 'text' => '#fafaf9', 'background' => '#171717', 'surface' => '#262626', 'muted' => 'rgba(231, 229, 228, 0.7)'],
            'font' => 'Playfair Display',
            'button_style' => 'rounded-pill',
            'hero_style' => 'authority-profile',
            'heading_scale' => 'lg',
            'section_order' => ['stats', 'trust_badges', 'benefits', 'gallery', 'testimonials', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'stats', 'trust_badges', 'benefits', 'gallery', 'testimonials', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'personal, meyakinkan, hangat',
            'cta_style' => 'dm-cta',
            'trust_elements' => ['Authority jelas', 'Personal touch', 'Siap diajak ngobrol'],
            'card_radius' => '2xl',
            'spacing_density' => 'comfortable',
            'background_pattern' => 'editorial-noise',
            'layout_style' => 'profile-led',
            'icon_style' => 'gold-frame',
        ],
        'agency-studio-design' => [
            'label' => 'Agency / Studio Design',
            'visual_mood' => 'creative-sharp',
            'palette' => ['primary' => '#22c55e', 'secondary' => '#dcfce7', 'accent' => '#a855f7', 'text' => '#f8fafc', 'background' => '#050816', 'surface' => '#0f172a', 'muted' => 'rgba(226, 232, 240, 0.72)'],
            'font' => 'Space Grotesk',
            'button_style' => 'sharp',
            'hero_style' => 'studio-case',
            'heading_scale' => 'xxl',
            'section_order' => ['gallery', 'comparison', 'process', 'stats', 'testimonials', 'pricing', 'faq', 'cta'],
            'recommended_sections' => ['hero', 'gallery', 'comparison', 'process', 'stats', 'testimonials', 'pricing', 'faq', 'cta'],
            'copy_tone' => 'confident, premium, creative',
            'cta_style' => 'consultation-glow',
            'trust_elements' => ['Creative direction', 'Studi kasus nyata', 'Consultation ready'],
            'card_radius' => 'xl',
            'spacing_density' => 'comfortable',
            'background_pattern' => 'grid-glow',
            'layout_style' => 'portfolio-led',
            'icon_style' => 'gradient-chip',
        ],
    ],
];
