<?php

return [
    'registry' => [
        'cta' => [
            'label' => 'CTA',
            'type' => 'cta',
            'description' => 'Ajakan tindakan utama.',
            'icon' => 'cursor-click',
            'supports_images' => false,
            'supports_cta' => true,
            'supports_repeater_items' => false,
            'default_content' => [
                'eyebrow' => 'Siap Ambil Langkah Berikutnya?',
                'title' => 'Arahkan pengunjung ke tindakan paling penting sekarang.',
                'description' => 'Bawa calon pembeli ke CTA yang paling penting.',
                'button' => 'Hubungi Sekarang',
                'link' => '#',
            ],
        ],
        'faq' => [
            'label' => 'FAQ',
            'type' => 'faq',
            'description' => 'Pertanyaan umum calon pembeli.',
            'icon' => 'help-circle',
            'supports_images' => false,
            'supports_cta' => false,
            'supports_repeater_items' => true,
            'default_content' => [
                'eyebrow' => 'FAQ',
                'title' => 'Pertanyaan yang sering ditanyakan',
                'items' => [
                    ['question' => 'Apakah ini bisa langsung dipakai?', 'answer' => 'Bisa, tinggal sesuaikan detailnya di editor.'],
                    ['question' => 'Apakah tampilannya bisa diubah?', 'answer' => 'Bisa, warna, teks, section, dan gambar bisa diedit.'],
                ],
            ],
        ],
        'pricing' => [
            'label' => 'Pricing',
            'type' => 'pricing',
            'description' => 'Harga utama dan benefit ringkas.',
            'icon' => 'wallet',
            'supports_images' => false,
            'supports_cta' => true,
            'supports_repeater_items' => true,
            'default_content' => [
                'eyebrow' => 'Penawaran',
                'title' => 'Harga yang paling mudah ditindaklanjuti',
                'price' => 'Rp 199.000',
                'items' => ['Benefit utama pertama', 'Benefit utama kedua', 'Bonus pendukung'],
                'cta_text' => 'Beli Sekarang',
                'cta_link' => '#',
            ],
        ],
        'testimonials' => [
            'label' => 'Testimonials',
            'type' => 'testimonials',
            'description' => 'Bukti sosial dan pengalaman pelanggan.',
            'icon' => 'message-circle',
            'supports_images' => false,
            'supports_cta' => false,
            'supports_repeater_items' => true,
            'default_content' => [
                'eyebrow' => 'Testimoni',
                'title' => 'Apa kata mereka setelah mencoba',
                'items' => [
                    ['name' => 'Pelanggan 1', 'quote' => 'Hasilnya lebih rapi dan lebih meyakinkan.'],
                    ['name' => 'Pelanggan 2', 'quote' => 'Lebih enak dibaca dan CTA-nya jelas.'],
                ],
            ],
        ],
        'package' => [
            'label' => 'Package',
            'type' => 'package',
            'description' => 'Beberapa paket penawaran.',
            'icon' => 'package',
            'supports_images' => false,
            'supports_cta' => false,
            'supports_repeater_items' => true,
            'default_content' => [
                'eyebrow' => 'Package Highlight',
                'title' => 'Bandingkan opsi penawaran dengan cepat',
                'items' => [
                    ['name' => 'Starter', 'price' => 'Rp 99.000', 'copy' => 'Cocok untuk mulai cepat.'],
                    ['name' => 'Best Value', 'price' => 'Rp 199.000', 'copy' => 'Paket utama dengan value seimbang.'],
                ],
            ],
        ],
        'features' => [
            'label' => 'Features',
            'type' => 'features',
            'description' => 'Poin fitur utama.',
            'icon' => 'layers',
            'supports_images' => false,
            'supports_cta' => false,
            'supports_repeater_items' => true,
            'default_content' => [
                'eyebrow' => 'Feature / Highlight',
                'title' => 'Fitur utama yang membuat offer lebih konkret',
                'items' => ['Feature 1', 'Feature 2', 'Feature 3'],
            ],
        ],
        'benefits' => [
            'label' => 'Benefits',
            'type' => 'benefits',
            'description' => 'Manfaat utama untuk target market.',
            'icon' => 'sparkles',
            'supports_images' => false,
            'supports_cta' => false,
            'supports_repeater_items' => true,
            'default_content' => [
                'eyebrow' => 'Manfaat Utama',
                'title' => 'Hal utama yang akan dirasakan pengunjung',
                'items' => ['Benefit 1', 'Benefit 2', 'Benefit 3'],
            ],
        ],
        'stats' => [
            'label' => 'Stats',
            'type' => 'stats',
            'description' => 'Angka atau indikator cepat.',
            'icon' => 'bar-chart-3',
            'supports_images' => false,
            'supports_cta' => false,
            'supports_repeater_items' => true,
            'default_content' => [
                'eyebrow' => 'Highlight Cepat',
                'title' => 'Data singkat yang mudah dipindai',
                'items' => [
                    ['value' => '03', 'label' => 'Benefit utama'],
                    ['value' => '04', 'label' => 'Feature unggulan'],
                    ['value' => '01', 'label' => 'CTA fokus'],
                ],
            ],
        ],
        'image' => [
            'label' => 'Image Gallery',
            'type' => 'image',
            'description' => 'Galeri grid beberapa gambar.',
            'icon' => 'image',
            'supports_images' => true,
            'supports_cta' => false,
            'supports_repeater_items' => true,
            'default_content' => [
                'eyebrow' => 'Galeri Produk',
                'title' => 'Beberapa tampilan visual utama',
                'subtitle' => 'Tambahkan beberapa foto untuk memperkuat first impression.',
                'layout' => 'grid-3',
                'items' => [
                    ['id' => 'img_1', 'image_url' => '', 'caption' => 'Front View'],
                    ['id' => 'img_2', 'image_url' => '', 'caption' => 'Lifestyle Shot'],
                ],
            ],
            'default_style' => [
                'card_radius' => 'xl',
                'gap' => 'md',
            ],
        ],
        'comparison' => [
            'label' => 'Comparison',
            'type' => 'comparison',
            'description' => 'Perbandingan before vs after atau opsi yang berbeda.',
            'icon' => 'git-compare',
            'supports_images' => false,
            'supports_cta' => false,
            'supports_repeater_items' => true,
            'default_content' => [
                'eyebrow' => 'Comparison',
                'title' => 'Bandingkan kondisi sebelum dan sesudah',
                'items' => [
                    ['title' => 'Sebelum', 'copy' => 'Masalah utama masih terasa membingungkan.'],
                    ['title' => 'Sesudah', 'copy' => 'Solusi dan CTA terasa lebih jelas.'],
                ],
            ],
        ],
        'process' => [
            'label' => 'Steps / Process',
            'type' => 'process',
            'description' => 'Alur kerja, langkah, atau proses.',
            'icon' => 'list-ordered',
            'supports_images' => false,
            'supports_cta' => false,
            'supports_repeater_items' => true,
            'default_content' => [
                'eyebrow' => 'Process',
                'title' => 'Langkah singkat yang mudah dipahami',
                'items' => [
                    ['title' => 'Step 1', 'copy' => 'Mulai dari highlight utama.'],
                    ['title' => 'Step 2', 'copy' => 'Masuk ke benefit dan value.'],
                    ['title' => 'Step 3', 'copy' => 'Akhiri dengan CTA yang jelas.'],
                ],
            ],
        ],
        'offer_stack' => [
            'label' => 'Bonus / Offer Stack',
            'type' => 'offer_stack',
            'description' => 'Tampilkan bonus atau stack value tambahan.',
            'icon' => 'gift',
            'supports_images' => false,
            'supports_cta' => false,
            'supports_repeater_items' => true,
            'default_content' => [
                'eyebrow' => 'Offer Stack',
                'title' => 'Tambahkan bonus dan value pendukung',
                'items' => [
                    ['title' => 'Bonus 1', 'copy' => 'Tambahan value yang memperkuat offer.'],
                    ['title' => 'Bonus 2', 'copy' => 'Membantu user lebih yakin.'],
                ],
            ],
        ],
        'portfolio' => [
            'label' => 'Portfolio / Showcase',
            'type' => 'portfolio',
            'description' => 'Showcase hasil, karya, atau galeri portofolio.',
            'icon' => 'briefcase',
            'supports_images' => true,
            'supports_cta' => false,
            'supports_repeater_items' => true,
            'default_content' => [
                'eyebrow' => 'Portfolio',
                'title' => 'Showcase visual untuk memperkuat kredibilitas',
                'items' => [
                    ['title' => 'Project 01', 'caption' => 'Contoh visual hasil.', 'image' => ''],
                    ['title' => 'Project 02', 'caption' => 'Bisa dipakai untuk dokumentasi atau campaign.', 'image' => ''],
                ],
            ],
        ],
        'guarantee' => [
            'label' => 'Guarantee / Trust',
            'type' => 'guarantee',
            'description' => 'Blok trust, assurance, atau guarantee.',
            'icon' => 'shield-check',
            'supports_images' => false,
            'supports_cta' => false,
            'supports_repeater_items' => true,
            'default_content' => [
                'eyebrow' => 'Guarantee',
                'title' => 'Tambahkan rasa aman sebelum CTA',
                'items' => [
                    ['title' => 'Aman & jelas', 'copy' => 'Proses dibuat lebih transparan.'],
                    ['title' => 'Support responsif', 'copy' => 'Pengunjung tahu langkah selanjutnya.'],
                ],
            ],
        ],
    ],
];
