<?php

return [
    'presets' => [
        [
            'name' => 'Soft Bloom',
            'slug' => 'soft-bloom',
            'description' => 'Soft, pastel, clean, feminine.',
            'palette' => ['primary' => '#f472b6', 'secondary' => '#fff1f5', 'accent' => '#c084fc', 'text' => '#4a2439', 'background' => '#fff8fb', 'surface' => '#fffdfd', 'muted' => 'rgba(74, 36, 57, 0.68)'],
            'font_preset' => 'Poppins',
            'radius' => '3xl',
            'button_style' => 'rounded-pill',
            'card_style' => 'soft-panel',
            'shadow_style' => 'soft',
            'hero_style' => 'soft-showcase',
            'section_spacing' => 'airy',
            'background_pattern' => 'soft-blur',
            'badge_style' => 'soft-pill',
            'recommended_niches' => ['skincare', 'salon-beauty-service', 'event-wedding'],
        ],
        [
            'name' => 'Mono Luxe',
            'slug' => 'mono-luxe',
            'description' => 'Monochrome premium, editorial, elegant.',
            'palette' => ['primary' => '#f8fafc', 'secondary' => '#e5e7eb', 'accent' => '#a1a1aa', 'text' => '#fafafa', 'background' => '#09090b', 'surface' => '#18181b', 'muted' => 'rgba(228, 228, 231, 0.72)'],
            'font_preset' => 'Playfair Display',
            'radius' => 'xl',
            'button_style' => 'luxury',
            'card_style' => 'glass-dark',
            'shadow_style' => 'deep',
            'hero_style' => 'editorial',
            'section_spacing' => 'airy',
            'background_pattern' => 'editorial-noise',
            'badge_style' => 'luxury-tag',
            'recommended_niches' => ['fashion', 'personal-branding', 'agency-studio-design'],
        ],
        [
            'name' => 'Sunset Punch',
            'slug' => 'sunset-punch',
            'description' => 'Warm, energetic, promo-heavy.',
            'palette' => ['primary' => '#fb923c', 'secondary' => '#ffedd5', 'accent' => '#ef4444', 'text' => '#fff7ed', 'background' => '#2a1207', 'surface' => '#3c1b0d', 'muted' => 'rgba(255, 237, 213, 0.72)'],
            'font_preset' => 'Poppins',
            'radius' => '2xl',
            'button_style' => 'rounded-pill',
            'card_style' => 'promo-card',
            'shadow_style' => 'warm',
            'hero_style' => 'promo-grid',
            'section_spacing' => 'comfortable',
            'background_pattern' => 'sunset-fade',
            'badge_style' => 'promo-badge',
            'recommended_niches' => ['makanan-minuman', 'travel'],
        ],
        [
            'name' => 'Ocean Glass',
            'slug' => 'ocean-glass',
            'description' => 'Fresh, airy, clean modern.',
            'palette' => ['primary' => '#06b6d4', 'secondary' => '#cffafe', 'accent' => '#60a5fa', 'text' => '#ecfeff', 'background' => '#082f49', 'surface' => '#0c4a6e', 'muted' => 'rgba(207, 250, 254, 0.72)'],
            'font_preset' => 'Plus Jakarta Sans',
            'radius' => '2xl',
            'button_style' => 'rounded-pill',
            'card_style' => 'glass-card',
            'shadow_style' => 'soft',
            'hero_style' => 'destination-banner',
            'section_spacing' => 'airy',
            'background_pattern' => 'soft-grid',
            'badge_style' => 'clean-tag',
            'recommended_niches' => ['travel', 'kesehatan-klinik', 'jasa'],
        ],
        [
            'name' => 'Bold Carbon',
            'slug' => 'bold-carbon',
            'description' => 'Dark, masculine, sharp.',
            'palette' => ['primary' => '#f97316', 'secondary' => '#ffedd5', 'accent' => '#facc15', 'text' => '#fafaf9', 'background' => '#09090b', 'surface' => '#18181b', 'muted' => 'rgba(245, 245, 244, 0.72)'],
            'font_preset' => 'Rajdhani',
            'radius' => 'xl',
            'button_style' => 'sharp',
            'card_style' => 'tech-card',
            'shadow_style' => 'deep',
            'hero_style' => 'bold-product',
            'section_spacing' => 'compact',
            'background_pattern' => 'grid-industrial',
            'badge_style' => 'sharp-tag',
            'recommended_niches' => ['helm', 'motor-jual-beli', 'otomotif-bengkel'],
        ],
        [
            'name' => 'Playful Pop',
            'slug' => 'playful-pop',
            'description' => 'Fun, colorful, young, active.',
            'palette' => ['primary' => '#22c55e', 'secondary' => '#dcfce7', 'accent' => '#f472b6', 'text' => '#f8fafc', 'background' => '#111827', 'surface' => '#1f2937', 'muted' => 'rgba(220, 252, 231, 0.72)'],
            'font_preset' => 'Poppins',
            'radius' => '3xl',
            'button_style' => 'rounded-pill',
            'card_style' => 'play-card',
            'shadow_style' => 'playful',
            'hero_style' => 'promo-grid',
            'section_spacing' => 'comfortable',
            'background_pattern' => 'grid-glow',
            'badge_style' => 'play-chip',
            'recommended_niches' => ['edukasi-course', 'makanan-minuman'],
        ],
        [
            'name' => 'Earth Craft',
            'slug' => 'earth-craft',
            'description' => 'Earthy, warm, natural.',
            'palette' => ['primary' => '#65a30d', 'secondary' => '#ecfccb', 'accent' => '#a16207', 'text' => '#fefce8', 'background' => '#1c1917', 'surface' => '#292524', 'muted' => 'rgba(236, 252, 203, 0.72)'],
            'font_preset' => 'Lora',
            'radius' => '3xl',
            'button_style' => 'rounded-lg',
            'card_style' => 'organic-card',
            'shadow_style' => 'warm',
            'hero_style' => 'wellness-soft',
            'section_spacing' => 'airy',
            'background_pattern' => 'organic-wash',
            'badge_style' => 'earth-badge',
            'recommended_niches' => ['herbal-wellness', 'furniture'],
        ],
        [
            'name' => 'Royal Velvet',
            'slug' => 'royal-velvet',
            'description' => 'Deep premium, rich, high-ticket.',
            'palette' => ['primary' => '#d4af37', 'secondary' => '#fef3c7', 'accent' => '#7c3aed', 'text' => '#faf5ff', 'background' => '#1e1b4b', 'surface' => '#312e81', 'muted' => 'rgba(233, 213, 255, 0.72)'],
            'font_preset' => 'Playfair Display',
            'radius' => '2xl',
            'button_style' => 'luxury',
            'card_style' => 'luxury-card',
            'shadow_style' => 'deep',
            'hero_style' => 'prestige-estate',
            'section_spacing' => 'airy',
            'background_pattern' => 'prestige-lines',
            'badge_style' => 'royal-tag',
            'recommended_niches' => ['properti', 'event-wedding', 'personal-branding'],
        ],
        [
            'name' => 'Future Neon',
            'slug' => 'future-neon',
            'description' => 'Neon modern, digital launch, tech-heavy.',
            'palette' => ['primary' => '#16f2a5', 'secondary' => '#d1fae5', 'accent' => '#38bdf8', 'text' => '#ecfeff', 'background' => '#03111a', 'surface' => '#0c1a24', 'muted' => 'rgba(220, 252, 231, 0.72)'],
            'font_preset' => 'Space Grotesk',
            'radius' => 'xl',
            'button_style' => 'sharp',
            'card_style' => 'neon-card',
            'shadow_style' => 'neon',
            'hero_style' => 'saas-split',
            'section_spacing' => 'comfortable',
            'background_pattern' => 'grid-glow',
            'badge_style' => 'neon-chip',
            'recommended_niches' => ['digital-product', 'edukasi-course', 'gadget-elektronik'],
        ],
        [
            'name' => 'Clean Commerce',
            'slug' => 'clean-commerce',
            'description' => 'Netral, sales-friendly, fallback universal.',
            'palette' => ['primary' => '#0ea5e9', 'secondary' => '#e0f2fe', 'accent' => '#10b981', 'text' => '#f8fafc', 'background' => '#0f172a', 'surface' => '#1e293b', 'muted' => 'rgba(226, 232, 240, 0.72)'],
            'font_preset' => 'Plus Jakarta Sans',
            'radius' => '2xl',
            'button_style' => 'rounded-lg',
            'card_style' => 'clean-card',
            'shadow_style' => 'soft',
            'hero_style' => 'simple-convert',
            'section_spacing' => 'normal',
            'background_pattern' => 'soft-grid',
            'badge_style' => 'clean-badge',
            'recommended_niches' => ['umkm-umum', 'jasa', 'digital-product', 'fashion', 'skincare'],
        ],
    ],
];
