<?php

return [
    'brand_colors' => [
        'Neutral/Monokrom',
        'Slate/Zinc',
        'Brand Orange',
        'Amber/Gold',
        'Red',
        'Rose/Pink',
        'Ocean Blue',
        'Sky Blue',
        'Indigo',
        'Violet/Purple',
        'Royal Purple',
        'Emerald Green',
        'Forest Green',
        'Teal/Cyan',
        'Lime Green',
        'Yellow',
        'Brown/Earthy',
        'Custom',
    ],
    'background_modes' => [
        'Default (Auto)',
        'Light Clean',
        'Dark Premium',
        'Gradient',
        'Grid Background',
        'Soft Pattern',
        'Noise Texture',
        'Minimal Flat',
    ],
    'fonts' => [
        'Plus Jakarta Sans', 'Poppins', 'Inter', 'Space Grotesk', 'DM Sans', 'Manrope',
        'Outfit', 'Urbanist', 'Sora', 'Work Sans', 'Archivo', 'Montserrat',
        'Lato', 'Nunito Sans', 'Cabin', 'Public Sans', 'Onest', 'Red Hat Display',
        'Playfair Display', 'Cormorant Garamond', 'Lora', 'Merriweather', 'Libre Baskerville',
        'DM Serif Display', 'Bodoni Moda', 'Prata', 'Fraunces', 'Newsreader',
        'Bebas Neue', 'Anton', 'Oswald', 'Barlow Condensed', 'Rajdhani', 'Saira',
        'Baloo 2', 'Fredoka', 'Quicksand', 'Figtree',
    ],
    'spacing_presets' => ['Compact', 'Balanced', 'Spacious', 'Luxury'],
];
